name: my_flutter
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  google_fonts: ^1.1.1
  flutter:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
  - assets/
  uses-material-design: true

fonts:
  - family: IndieFlower
    fonts:
      - asset: fonts/IndieFlower-Regular.ttf
uses-material-design: true